CREATE TABLE IF NOT EXISTS `Application`
( 
`Id` INTEGER PRIMARY KEY AUTOINCREMENT
, `ExternalId` TEXT NOT NULL UNIQUE
, `Name` TEXT NOT NULL UNIQUE
, `PrivateKey` TEXT NOT NULL
, `PublicKey` TEXT NOT NULL 
)